### ISSUE TITLE
this plugin not working

### ISSUE THREAD

**Issue by CARocha** [Destiny-Ed/flutter_youtube_downloader#3]
Hi, i try several link the youtube but not working only say Dowload link is bkoken or not available for download!!
i used flutter version 1.22.6
any helps??

**Comment by Destiny-Ed** [comment]
I will check that later

**Comment by Destiny-Ed** [comment]
Make sure you remove any "..." Dots from the video title

**Comment by CARocha** [comment]
Hi, @Destiny-Ed yes i remove ... Dots the video title and this works, one question more, is posible back the path where the video saved? i will like saved and then play with flutter video_player like chewie in asset mode.

**Comment by Destiny-Ed** [comment]
Glad it worked for you. Concerning the video download part, they are saved
in your phones Download directory. So you can find them there.

Or if there's any functionality you want the plugin to have just let me know

**Comment by CARocha** [comment]
@Destiny-Ed thank it work very well, i try saved many video.

I have changed your example I have put 2 TextField one for name of video and other for link to video and change the function

Future<String> downloadVideo(String link, String name) async {
    final result = await FlutterYoutubeDownloader.downloadVideo(
        link, "$name", 18);
    return result;
  }

and floatingActionButton a put this

floatingActionButton: FloatingActionButton(
          onPressed: (){
            downloadVideo(_controller1.text,_controller2.text);
          },
          child: const Icon(Icons.download_rounded),
        ),

and the videos are downloaded completely well.

Now what I want to do is when I put a link and the name touch download video, once I download it, it can be seen below in a video_player but there I am stuck

Thanks for answering, if you have an example of how to search the video by its name and be able to present it under the TextFields either with a future builder or something like that. 

Cheers
