### ISSUE TITLE
download for ios

### ISSUE THREAD

**Issue by CARocha** [Destiny-Ed/flutter_youtube_downloader#4]
Hi, i try to dowload video in iphone 12 not simulator, real device but not dowload this plugins is compatible for iOS 14.5?

Cheers

**Comment by Destiny-Ed** [comment]
Hello, sorry to inform you that this plugin is not yet available for iOS. I would really appreciate a contribution if it's something you or anyone can work on.

**Comment by amanokerim** [comment]
@Destiny-Ed PLEASE 🙏🏼   inform that this plugin supports only Android in a readme file.
P.S. This is great idea and plugin)
