### ISSUE TITLE
not yet compatible with null-safety?

### ISSUE THREAD

**Issue by CARocha** [Destiny-Ed/flutter_youtube_downloader#5]
Hi, when migrate my app to dart (2.13.0) and flutter (2.2.2 ) null-safety this packages in marked incompatible!

**Comment by Destiny-Ed** [comment]
Yeah, it's still in legacy. But it will still work better if you migrate to
null safety

**Comment by CARocha** [comment]
@Destiny-Ed You still do not have plans to migrate it?

**Comment by Destiny-Ed** [comment]
Am currently working on that. I will release the null safety version
very soon

**Comment by Destiny-Ed** [comment]
Null safety version has been released. Check it out on pub.dev
