### ISSUE TITLE
Failed to get iTag Url 

### ISSUE THREAD

**Issue by sherifElawdey** [Destiny-Ed/flutter_youtube_downloader#7]
When I extract the url, it gives me this error
what is the reason؟؟؟

**Comment by sherifElawdey** [comment]
??

**Comment by Destiny-Ed** [comment]
Are you using a valid YouTube video url?

**Comment by sherifElawdey** [comment]
yes

**Comment by sherifElawdey** [comment]
like this  https://www.youtube.com/watch?v=cI4ryatVkKw

**Comment by Destiny-Ed** [comment]
I tested the url and it's working fine
https://www.youtube.com/watch?v=cI4ryatVkKw

Are you sure you are implementing it correctly?

Check the example app please

**Comment by sherifElawdey** [comment]
The download was successful but when I extract the url from the youtube link it gives me failed to get iTag url
and I got your code copy ,paste

**Comment by sherifElawdey** [comment]
@Destiny-Ed  I checked your example on gethup and I knew where the error is. Thank you very much, but I have a question, can I download any link other than the YouTube link, such as a Facebook video, Instagram or Tiktok
and extract the url from them؟؟

**Comment by Destiny-Ed** [comment]
Nice you identified the error. The plugin only allows you to extract and download YouTube videos. But am currently working on Facebook and Instagram plugin

**Comment by sherifElawdey** [comment]
Thanks, I'm waiting for this plugin

**Comment by Destiny-Ed** [comment]
Alright sheriff

 Subscribe to my channel if you haven't so that you will receive
notification when I upload the plugin video

https://youtube.com/channel/UCFEtn_pdpZPT9vMxovgTp0A

**Comment by sherifElawdey** [comment]
Thank you, I will do that.
